### ISSUE TITLE
[Help]: CUDA Failure : an illegal instruction was encountered

### ISSUE THREAD

**Issue by LyhXXBUAA** [laugh12321/TensorRT-YOLO#105]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

作者您好 我将deploy文件夹放在了我的项目中 编译生成了动态库 然后将examples/detect.cpp的内容放在了一个新的文件中并编译成了可执行文件 但是当我执行该可执行文件时报错 lyh@yuanhaoLao:~/Code/VSCode/graduation_PRJ/build/tests$ ./test_detect 
CUDA Failure at /home/lyh/Code/VSCode/graduation_PRJ/deploy/core/core.cpp:117: an illegal instruction was encountered 报错的地方显示在

![Image](https://github.com/user-attachments/assets/1ae95033-919e-431b-ba97-37eecc88bb08)这个函数中 当我断点debug 发现报错出现在程序进入到predict函数时

![Image](https://github.com/user-attachments/assets/e2b64341-bbe5-4832-a624-fe1204eb71e5) 

我的显卡为RTX4080 cuda版本为12.3 tensorrt为TensorRT-10.7.0.23.Linux.x86_64-gnu.cuda-12.6 请问您知道这是什么原因导致的吗

**Comment by laugh12321** [comment]
@LyhXXBUAA 请问直接在这个仓库编译`deploy`和`examples`是否也会出现上述问题？

**Comment by laugh12321** [comment]
@LyhXXBUAA 请问直接在这个仓库编译`deploy`和`examples`是否也会出现上述问题？

同时检查一下，GPU驱动是否安装。

**Comment by laugh12321** [comment]
@LyhXXBUAA 你导出的onnx是使用`trtyolo`导出的吗？可以发一下netron可视化的输出头吗

**Comment by LyhXXBUAA** [comment]
我的onnx使用yolov10自带的导出方式导出的

![Image](https://github.com/user-attachments/assets/15c57144-b5ab-459d-b28b-6eeecaefe1c6)
(他提供的导出方式会有问题吗QAQ
这是我的模型的netron可视化

![Image](https://github.com/user-attachments/assets/99333a52-72cf-421b-910b-7c1b509b3e65)

**Comment by laugh12321** [comment]
@LyhXXBUAA 请仔细看文档，需要使用`trtyolo`导出符合这个项目的ONNX。你这样肯定会出问题的

**Comment by LyhXXBUAA** [comment]
> [@LyhXXBUAA](https://github.com/LyhXXBUAA) 请仔细看文档，需要使用`trtyolo`导出符合这个项目的ONNX。你这样肯定会出问题的

好的 我去试一下trtyolo导出 因为我看主页的性能对比以为能用官方提供的onnx导出方式

**Comment by laugh12321** [comment]
@LyhXXBUAA 主页的对比是为了突出使用这个项目的优势 （`trtyolo` export + TensorRT-YOLO Inference）

**Comment by LyhXXBUAA** [comment]
感谢您的您的耐心解答 问题已解决！用您的trtyolo转的话就不会报错了
还想请教一下别的模型(例如语义分割 立体匹配)能否在您的这个框架基础上修改进行Tensorrt的部署呢 还是说该框架仅支持Yolo系列呢

**Comment by laugh12321** [comment]
@LyhXXBUAA 请查看[模型支持列表](https://github.com/laugh12321/TensorRT-YOLO/tree/11e47685d2ffcec9aa270272532ba96c020ae1cf?tab=readme-ov-file#%EF%B8%8F-%E6%A8%A1%E5%9E%8B%E6%94%AF%E6%8C%81%E5%88%97%E8%A1%A8)

**Comment by LyhXXBUAA** [comment]
> [@LyhXXBUAA](https://github.com/LyhXXBUAA) 请查看[模型支持列表](https://github.com/laugh12321/TensorRT-YOLO/tree/11e47685d2ffcec9aa270272532ba96c020ae1cf?tab=readme-ov-file#%EF%B8%8F-%E6%A8%A1%E5%9E%8B%E6%94%AF%E6%8C%81%E5%88%97%E8%A1%A8)

好的！

**Comment by laugh12321** [comment]
@LyhXXBUAA 没有别的问题的话，这个issue即将关闭。

**Comment by LyhXXBUAA** [comment]
> [@LyhXXBUAA](https://github.com/LyhXXBUAA) 没有别的问题的话，这个issue即将关闭。

暂时没别的问题啦 感谢！
