### ISSUE TITLE
[Help]: invalid device function

### ISSUE THREAD

**Issue by youwyu** [laugh12321/TensorRT-YOLO#74]
### Search before asking

- [X] I have searched the question and found no related answer.

### Please ask your question

The error shows as below
```bash
TensorRT-YOLO/examples/detect$ python3 detect.py -e models/yolo11n.engine -i images -o output -l labels.txt --cudaGraph
CUDA Error:
    File:       TensorRT-YOLO/source/deploy/vision/inference.cpp
    Line:       558
    Error code: 98
    Error text: invalid device function
[I] Infering data in images
Processing batches ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Segmentation fault (core dumped)
```

The thing I changed in CMakeLists to make the code build
```bash
# cmake_policy(SET CMP0146 OLD)

# set(CMAKE_CUDA_ARCHITECTURES native)
set(CMAKE_CUDA_ARCHITECTURES 89)
```

**Comment by laugh12321** [comment]
@youwyu Your GPU's compute capability might not be 8.9. Please visit [NVIDIA CUDA GPUs](https://developer.nvidia.com/cuda-gpus) to check and set the correct compute capability. For a similar issue, you can refer to [this Stack Overflow question](https://stackoverflow.com/questions/28451859/cuda-invalid-device-function-how-to-know-architecture-code).

**Comment by youwyu** [comment]
Thank you! It perfectly solved my issue.
